// flow-typed signature: 99706eae19bead6f0c47d1271ff1f6a7
// flow-typed version: <<STUB>>/lodash.memoize_v4.1.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.memoize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.memoize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.memoize/index' {
  declare module.exports: $Exports<'lodash.memoize'>;
}
declare module 'lodash.memoize/index.js' {
  declare module.exports: $Exports<'lodash.memoize'>;
}
