// flow-typed signature: 346c0b8098ab17bcd458d2ee87e8ec37
// flow-typed version: <<STUB>>/next_v2.0.0-beta.12/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next/babel' {
  declare module.exports: any;
}

declare module 'next/css' {
  declare module.exports: any;
}

declare module 'next/dist/client/head-manager' {
  declare module.exports: any;
}

declare module 'next/dist/client/next-dev' {
  declare module.exports: any;
}

declare module 'next/dist/client/next-prefetcher-bundle' {
  declare module.exports: any;
}

declare module 'next/dist/client/next-prefetcher' {
  declare module.exports: any;
}

declare module 'next/dist/client/next' {
  declare module.exports: any;
}

declare module 'next/dist/client/webpack-hot-middleware-client' {
  declare module.exports: any;
}

declare module 'next/dist/lib/app' {
  declare module.exports: any;
}

declare module 'next/dist/lib/css' {
  declare module.exports: any;
}

declare module 'next/dist/lib/eval-script' {
  declare module.exports: any;
}

declare module 'next/dist/lib/head' {
  declare module.exports: any;
}

declare module 'next/dist/lib/link' {
  declare module.exports: any;
}

declare module 'next/dist/lib/prefetch' {
  declare module.exports: any;
}

declare module 'next/dist/lib/router/index' {
  declare module.exports: any;
}

declare module 'next/dist/lib/router/router' {
  declare module.exports: any;
}

declare module 'next/dist/lib/shallow-equals' {
  declare module.exports: any;
}

declare module 'next/dist/lib/side-effect' {
  declare module.exports: any;
}

declare module 'next/dist/lib/utils' {
  declare module.exports: any;
}

declare module 'next/dist/pages/_document' {
  declare module.exports: any;
}

declare module 'next/dist/pages/_error-debug' {
  declare module.exports: any;
}

declare module 'next/dist/pages/_error' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/babel/preset' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/clean' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/gzip' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/index' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/loaders/emit-file-loader' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/loaders/hot-self-accept-loader' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/detach-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/dynamic-entry-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/json-pages-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/unlink-file-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/watch-pages-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/watch-remove-event-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/webpack' {
  declare module.exports: any;
}

declare module 'next/dist/server/config' {
  declare module.exports: any;
}

declare module 'next/dist/server/document' {
  declare module.exports: any;
}

declare module 'next/dist/server/hot-reloader' {
  declare module.exports: any;
}

declare module 'next/dist/server/index' {
  declare module.exports: any;
}

declare module 'next/dist/server/next' {
  declare module.exports: any;
}

declare module 'next/dist/server/read-page' {
  declare module.exports: any;
}

declare module 'next/dist/server/render' {
  declare module.exports: any;
}

declare module 'next/dist/server/require' {
  declare module.exports: any;
}

declare module 'next/dist/server/resolve' {
  declare module.exports: any;
}

declare module 'next/dist/server/router' {
  declare module.exports: any;
}

declare module 'next/document' {
  declare module.exports: any;
}

declare module 'next/head' {
  declare module.exports: any;
}

declare module 'next/link' {
  declare module.exports: any;
}

declare module 'next/prefetch' {
  declare module.exports: any;
}

declare module 'next/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next/babel.js' {
  declare module.exports: $Exports<'next/babel'>;
}
declare module 'next/css.js' {
  declare module.exports: $Exports<'next/css'>;
}
declare module 'next/dist/client/head-manager.js' {
  declare module.exports: $Exports<'next/dist/client/head-manager'>;
}
declare module 'next/dist/client/next-dev.js' {
  declare module.exports: $Exports<'next/dist/client/next-dev'>;
}
declare module 'next/dist/client/next-prefetcher-bundle.js' {
  declare module.exports: $Exports<'next/dist/client/next-prefetcher-bundle'>;
}
declare module 'next/dist/client/next-prefetcher.js' {
  declare module.exports: $Exports<'next/dist/client/next-prefetcher'>;
}
declare module 'next/dist/client/next.js' {
  declare module.exports: $Exports<'next/dist/client/next'>;
}
declare module 'next/dist/client/webpack-hot-middleware-client.js' {
  declare module.exports: $Exports<'next/dist/client/webpack-hot-middleware-client'>;
}
declare module 'next/dist/lib/app.js' {
  declare module.exports: $Exports<'next/dist/lib/app'>;
}
declare module 'next/dist/lib/css.js' {
  declare module.exports: $Exports<'next/dist/lib/css'>;
}
declare module 'next/dist/lib/eval-script.js' {
  declare module.exports: $Exports<'next/dist/lib/eval-script'>;
}
declare module 'next/dist/lib/head.js' {
  declare module.exports: $Exports<'next/dist/lib/head'>;
}
declare module 'next/dist/lib/link.js' {
  declare module.exports: $Exports<'next/dist/lib/link'>;
}
declare module 'next/dist/lib/prefetch.js' {
  declare module.exports: $Exports<'next/dist/lib/prefetch'>;
}
declare module 'next/dist/lib/router/index.js' {
  declare module.exports: $Exports<'next/dist/lib/router/index'>;
}
declare module 'next/dist/lib/router/router.js' {
  declare module.exports: $Exports<'next/dist/lib/router/router'>;
}
declare module 'next/dist/lib/shallow-equals.js' {
  declare module.exports: $Exports<'next/dist/lib/shallow-equals'>;
}
declare module 'next/dist/lib/side-effect.js' {
  declare module.exports: $Exports<'next/dist/lib/side-effect'>;
}
declare module 'next/dist/lib/utils.js' {
  declare module.exports: $Exports<'next/dist/lib/utils'>;
}
declare module 'next/dist/pages/_document.js' {
  declare module.exports: $Exports<'next/dist/pages/_document'>;
}
declare module 'next/dist/pages/_error-debug.js' {
  declare module.exports: $Exports<'next/dist/pages/_error-debug'>;
}
declare module 'next/dist/pages/_error.js' {
  declare module.exports: $Exports<'next/dist/pages/_error'>;
}
declare module 'next/dist/server/build/babel/preset.js' {
  declare module.exports: $Exports<'next/dist/server/build/babel/preset'>;
}
declare module 'next/dist/server/build/clean.js' {
  declare module.exports: $Exports<'next/dist/server/build/clean'>;
}
declare module 'next/dist/server/build/gzip.js' {
  declare module.exports: $Exports<'next/dist/server/build/gzip'>;
}
declare module 'next/dist/server/build/index.js' {
  declare module.exports: $Exports<'next/dist/server/build/index'>;
}
declare module 'next/dist/server/build/loaders/emit-file-loader.js' {
  declare module.exports: $Exports<'next/dist/server/build/loaders/emit-file-loader'>;
}
declare module 'next/dist/server/build/loaders/hot-self-accept-loader.js' {
  declare module.exports: $Exports<'next/dist/server/build/loaders/hot-self-accept-loader'>;
}
declare module 'next/dist/server/build/plugins/detach-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/detach-plugin'>;
}
declare module 'next/dist/server/build/plugins/dynamic-entry-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/dynamic-entry-plugin'>;
}
declare module 'next/dist/server/build/plugins/json-pages-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/json-pages-plugin'>;
}
declare module 'next/dist/server/build/plugins/unlink-file-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/unlink-file-plugin'>;
}
declare module 'next/dist/server/build/plugins/watch-pages-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/watch-pages-plugin'>;
}
declare module 'next/dist/server/build/plugins/watch-remove-event-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/watch-remove-event-plugin'>;
}
declare module 'next/dist/server/build/webpack.js' {
  declare module.exports: $Exports<'next/dist/server/build/webpack'>;
}
declare module 'next/dist/server/config.js' {
  declare module.exports: $Exports<'next/dist/server/config'>;
}
declare module 'next/dist/server/document.js' {
  declare module.exports: $Exports<'next/dist/server/document'>;
}
declare module 'next/dist/server/hot-reloader.js' {
  declare module.exports: $Exports<'next/dist/server/hot-reloader'>;
}
declare module 'next/dist/server/index.js' {
  declare module.exports: $Exports<'next/dist/server/index'>;
}
declare module 'next/dist/server/next.js' {
  declare module.exports: $Exports<'next/dist/server/next'>;
}
declare module 'next/dist/server/read-page.js' {
  declare module.exports: $Exports<'next/dist/server/read-page'>;
}
declare module 'next/dist/server/render.js' {
  declare module.exports: $Exports<'next/dist/server/render'>;
}
declare module 'next/dist/server/require.js' {
  declare module.exports: $Exports<'next/dist/server/require'>;
}
declare module 'next/dist/server/resolve.js' {
  declare module.exports: $Exports<'next/dist/server/resolve'>;
}
declare module 'next/dist/server/router.js' {
  declare module.exports: $Exports<'next/dist/server/router'>;
}
declare module 'next/document.js' {
  declare module.exports: $Exports<'next/document'>;
}
declare module 'next/head.js' {
  declare module.exports: $Exports<'next/head'>;
}
declare module 'next/link.js' {
  declare module.exports: $Exports<'next/link'>;
}
declare module 'next/prefetch.js' {
  declare module.exports: $Exports<'next/prefetch'>;
}
declare module 'next/router.js' {
  declare module.exports: $Exports<'next/router'>;
}
