// flow-typed signature: 9c09c00b943f878ff3ac53644a5d106d
// flow-typed version: <<STUB>>/redux-promise-memo_v0.2.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise-memo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise-memo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-promise-memo/__tests__/memoize.test' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/lib/config' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/lib/createReducer' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/lib/enhancer' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/lib/index' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/lib/memoize' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/lib/promiseMiddleware' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/lib/types' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/src/config' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/src/createReducer' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/src/enhancer' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/src/index' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/src/memoize' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/src/promiseMiddleware' {
  declare module.exports: any;
}

declare module 'redux-promise-memo/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-promise-memo/__tests__/memoize.test.js' {
  declare module.exports: $Exports<'redux-promise-memo/__tests__/memoize.test'>;
}
declare module 'redux-promise-memo/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'redux-promise-memo/coverage/lcov-report/prettify'>;
}
declare module 'redux-promise-memo/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'redux-promise-memo/coverage/lcov-report/sorter'>;
}
declare module 'redux-promise-memo/lib/config.js' {
  declare module.exports: $Exports<'redux-promise-memo/lib/config'>;
}
declare module 'redux-promise-memo/lib/createReducer.js' {
  declare module.exports: $Exports<'redux-promise-memo/lib/createReducer'>;
}
declare module 'redux-promise-memo/lib/enhancer.js' {
  declare module.exports: $Exports<'redux-promise-memo/lib/enhancer'>;
}
declare module 'redux-promise-memo/lib/index.js' {
  declare module.exports: $Exports<'redux-promise-memo/lib/index'>;
}
declare module 'redux-promise-memo/lib/memoize.js' {
  declare module.exports: $Exports<'redux-promise-memo/lib/memoize'>;
}
declare module 'redux-promise-memo/lib/promiseMiddleware.js' {
  declare module.exports: $Exports<'redux-promise-memo/lib/promiseMiddleware'>;
}
declare module 'redux-promise-memo/lib/types.js' {
  declare module.exports: $Exports<'redux-promise-memo/lib/types'>;
}
declare module 'redux-promise-memo/src/config.js' {
  declare module.exports: $Exports<'redux-promise-memo/src/config'>;
}
declare module 'redux-promise-memo/src/createReducer.js' {
  declare module.exports: $Exports<'redux-promise-memo/src/createReducer'>;
}
declare module 'redux-promise-memo/src/enhancer.js' {
  declare module.exports: $Exports<'redux-promise-memo/src/enhancer'>;
}
declare module 'redux-promise-memo/src/index.js' {
  declare module.exports: $Exports<'redux-promise-memo/src/index'>;
}
declare module 'redux-promise-memo/src/memoize.js' {
  declare module.exports: $Exports<'redux-promise-memo/src/memoize'>;
}
declare module 'redux-promise-memo/src/promiseMiddleware.js' {
  declare module.exports: $Exports<'redux-promise-memo/src/promiseMiddleware'>;
}
declare module 'redux-promise-memo/src/types.js' {
  declare module.exports: $Exports<'redux-promise-memo/src/types'>;
}
